# Generated by Django 4.2.7 on 2023-12-11 07:07

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='photos/products'),
        ),
    ]
