# Generated by Django 4.2.7 on 2024-01-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='Wishlist',
            new_name='wishlist',
        ),
    ]
