# Generated by Django 4.2.7 on 2023-12-11 06:39

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='banner/images/')),
                ('url', models.URLField(blank=True, default='#')),
                ('button_text', models.CharField(default='Buy Now', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
