# Generated by Django 4.2.7 on 2023-12-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_management', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='banner',
        ),
    ]
