# Generated by Django 4.2.7 on 2023-12-11 08:14

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('banner_management', '0004_rename_image_banner_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='name',
            new_name='banner_name',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='photos/banners/'),
        ),
    ]
