# Generated by Django 4.2.7 on 2023-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_management', '0005_rename_name_banner_banner_name_alter_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='photos/banners/'),
        ),
    ]
