# Generated by Django 4.2.5 on 2023-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
