# Generated by Django 4.2.7 on 2023-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_coupon_alter_address_country_alter_address_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order_Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out_for_delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
