# Generated by Django 4.2.7 on 2024-01-18 15:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='AF', max_length=200),
            preserve_default=False,
        ),
    ]
